### ISSUE TITLE
useResource: Loading still "true" even after Error received

### ISSUE THREAD

**Issue by pschwyter** [badgateway/react-ketting#95]
I think this is a bug? I would expect that `loading` is `false` once we either have `data` or an `error` returned by `useResource`

<img width="803" alt="image" src="https://user-images.githubusercontent.com/4810916/175318824-e1378cf4-f21d-42a5-9625-06ebc61d2317.png">

**Comment by pschwyter** [comment]
Just to be clear, I know *why* this failed/404'd. But this still feels like a bug and shouldn't happen

**Comment by evert** [comment]
Agreed! Definitely a bug
